---
- hosts: webservers
  become: yes
  become_user: root
  become_method: sudo
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/
    max_clients: 5

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"
  
  - name: Ensure that Apache is installed
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started

  - name: Deploy configuration File
    template: src=templates/apache2.j2 dest=/etc/apache2/conf-available/apache2.conf
    notify:
      - Restart Apache

  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html

  handlers:
     - name: Restart Apache
       service: name=apache2 state=restarted

- hosts: dbservers
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
  - name: Ensure MySQL is installed
    apt: name=mysql-server state=present
    when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

  - name: Start MySQL
    service: name=mysql state=started
    
  - name: Save the result of 'whoami' in 'whoami_out'
    win_command: whoami
    register: whoami_out
